import type { NewsSource } from "./types";

/**
 * Default source registry (spec §47, cost §121).
 * Fast group: breaking-capable RSS + GDELT + HN + GitHub watchlist.
 * Normal group: regular RSS, company blogs, arXiv, HF.
 * Authority scores follow cost spec §29.
 */
export const DEFAULT_SOURCES: NewsSource[] = [
  // ── Fast: breaking wire / tech media RSS ──────────────────────────
  {
    id: "rss-bbc-world",
    name: "BBC World",
    type: "rss",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    provider: "rss",
    category: "World",
    language: "en",
    country: "UK",
    authorityScore: 88,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-reuters-top",
    name: "Reuters Top News",
    type: "rss",
    url: "https://news.google.com/rss/search?q=when:1h+allinurl:reuters.com&hl=en-US&gl=US&ceid=US:en",
    provider: "rss",
    category: "World",
    language: "en",
    country: "US",
    authorityScore: 90,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-aljazeera",
    name: "Al Jazeera",
    type: "rss",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    provider: "rss",
    category: "World",
    language: "en",
    country: "QA",
    authorityScore: 85,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-techcrunch",
    name: "TechCrunch",
    type: "rss",
    url: "https://techcrunch.com/feed/",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 80,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-verge",
    name: "The Verge",
    type: "rss",
    url: "https://www.theverge.com/rss/index.xml",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 78,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-ars-technica",
    name: "Ars Technica",
    type: "rss",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 78,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-venturebeat-ai",
    name: "VentureBeat AI",
    type: "rss",
    url: "https://venturebeat.com/category/ai/feed/",
    provider: "rss",
    category: "AI",
    language: "en",
    country: "US",
    authorityScore: 74,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-the-hacker-news",
    name: "The Hacker News",
    type: "rss",
    url: "https://feeds.feedburner.com/TheHackersNews",
    provider: "rss",
    category: "Cybersecurity",
    language: "en",
    country: "IN",
    authorityScore: 70,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-cnbc-markets",
    name: "CNBC Markets",
    type: "rss",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss25&id=20910258",
    provider: "rss",
    category: "Markets",
    language: "en",
    country: "US",
    authorityScore: 84,
    enabled: true,
    refreshIntervalMinutes: 10,
    group: "fast",
  },
  {
    id: "rss-wired",
    name: "Wired",
    type: "rss",
    url: "https://www.wired.com/feed/rss",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 80,
    enabled: true,
    refreshIntervalMinutes: 15,
    group: "fast",
  },
  {
    id: "rss-engadget",
    name: "Engadget",
    type: "rss",
    url: "https://www.engadget.com/rss.xml",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 75,
    enabled: true,
    refreshIntervalMinutes: 15,
    group: "fast",
  },
  {
    id: "rss-npr-world",
    name: "NPR World",
    type: "rss",
    url: "https://feeds.npr.org/1004/rss.xml",
    provider: "rss",
    category: "World",
    language: "en",
    country: "US",
    authorityScore: 86,
    enabled: true,
    refreshIntervalMinutes: 15,
    group: "fast",
  },
  {
    id: "rss-gnews-top",
    name: "Google News Top",
    type: "rss",
    url: "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
    provider: "rss",
    category: "World",
    language: "en",
    country: "US",
    authorityScore: 82,
    enabled: true,
    refreshIntervalMinutes: 15,
    group: "fast",
  },
  {
    id: "rss-bleepingcomputer",
    name: "BleepingComputer",
    type: "rss",
    url: "https://www.bleepingcomputer.com/feed/",
    provider: "rss",
    category: "Cybersecurity",
    language: "en",
    country: "US",
    authorityScore: 72,
    enabled: true,
    refreshIntervalMinutes: 20,
    group: "fast",
  },

  // ── Fast: API discovery layers ────────────────────────────────────
  {
    id: "gdelt-global",
    name: "GDELT Global Radar",
    type: "api",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    provider: "gdelt",
    category: "World",
    language: "en",
    authorityScore: 82,
    enabled: true,
    refreshIntervalMinutes: 15,
    group: "fast",
  },
  {
    id: "hn-top",
    name: "Hacker News",
    type: "api",
    url: "https://hacker-news.firebaseio.com/v0",
    provider: "hackernews",
    category: "Technology",
    language: "en",
    authorityScore: 72,
    enabled: true,
    refreshIntervalMinutes: 15,
    group: "fast",
  },
  {
    id: "github-watchlist",
    name: "GitHub Watchlist",
    type: "api",
    url: "https://api.github.com",
    provider: "github",
    category: "OpenSource",
    language: "en",
    authorityScore: 85,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "fast",
  },

  // ── Normal: official blogs (first-party, high authority) ──────────
  {
    id: "rss-openai-blog",
    name: "OpenAI Blog",
    type: "official",
    url: "https://openai.com/news/rss.xml",
    provider: "rss",
    category: "AI",
    language: "en",
    country: "US",
    authorityScore: 95,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-anthropic-news",
    name: "Anthropic News",
    type: "official",
    url: "https://www.anthropic.com/rss.xml",
    provider: "rss",
    category: "AI",
    language: "en",
    country: "US",
    authorityScore: 95,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-deepmind-blog",
    name: "Google DeepMind Blog",
    type: "official",
    url: "https://deepmind.google/blog/rss.xml",
    provider: "rss",
    category: "AI",
    language: "en",
    country: "US",
    authorityScore: 95,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-meta-ai",
    name: "Meta AI Blog",
    type: "official",
    url: "https://ai.meta.com/blog/rss/",
    provider: "rss",
    category: "AI",
    language: "en",
    country: "US",
    authorityScore: 92,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-hf-blog",
    name: "Hugging Face Blog",
    type: "official",
    url: "https://huggingface.co/blog/feed.xml",
    provider: "rss",
    category: "AI",
    language: "en",
    country: "US",
    authorityScore: 90,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-github-blog",
    name: "GitHub Blog",
    type: "official",
    url: "https://github.blog/feed/",
    provider: "rss",
    category: "OpenSource",
    language: "en",
    country: "US",
    authorityScore: 90,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-cloudflare-blog",
    name: "Cloudflare Blog",
    type: "official",
    url: "https://blog.cloudflare.com/rss/",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 88,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-nvidia-blog",
    name: "NVIDIA Blog",
    type: "official",
    url: "https://blogs.nvidia.com/feed/",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 92,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-microsoft-research",
    name: "Microsoft Research",
    type: "official",
    url: "https://www.microsoft.com/en-us/research/feed/",
    provider: "rss",
    category: "Science",
    language: "en",
    country: "US",
    authorityScore: 90,
    enabled: true,
    refreshIntervalMinutes: 60,
    group: "normal",
  },

  // ── Normal: expanded tech / science / security / business coverage ──
  {
    id: "rss-the-register",
    name: "The Register",
    type: "rss",
    url: "https://www.theregister.com/feed/",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "UK",
    authorityScore: 74,
    enabled: true,
    refreshIntervalMinutes: 30,
    group: "normal",
  },
  {
    id: "rss-mit-tr",
    name: "MIT Technology Review",
    type: "rss",
    url: "https://www.technologyreview.com/feed/",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 85,
    enabled: true,
    refreshIntervalMinutes: 60,
    group: "normal",
  },
  {
    id: "rss-ieee-spectrum",
    name: "IEEE Spectrum",
    type: "rss",
    url: "https://spectrum.ieee.org/feeds/feed.rss",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 80,
    enabled: true,
    refreshIntervalMinutes: 60,
    group: "normal",
  },
  {
    id: "rss-apple-newsroom",
    name: "Apple Newsroom",
    type: "official",
    url: "https://www.apple.com/newsroom/rss-feed.rss",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 92,
    enabled: true,
    refreshIntervalMinutes: 60,
    group: "normal",
  },
  {
    id: "rss-google-blog",
    name: "Google Blog",
    type: "official",
    url: "https://blog.google/rss/",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 92,
    enabled: true,
    refreshIntervalMinutes: 60,
    group: "normal",
  },
  {
    id: "rss-microsoft-blog",
    name: "Microsoft Blog",
    type: "official",
    url: "https://blogs.microsoft.com/feed/",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 90,
    enabled: true,
    refreshIntervalMinutes: 60,
    group: "normal",
  },
  {
    id: "rss-aws-news",
    name: "AWS What's New",
    type: "official",
    url: "https://aws.amazon.com/about-aws/whats-new/recent/feed/",
    provider: "rss",
    category: "Technology",
    language: "en",
    country: "US",
    authorityScore: 88,
    enabled: true,
    refreshIntervalMinutes: 60,
    group: "normal",
  },
  {
    id: "rss-securityweek",
    name: "SecurityWeek",
    type: "rss",
    url: "https://www.securityweek.com/feed/",
    provider: "rss",
    category: "Cybersecurity",
    language: "en",
    country: "US",
    authorityScore: 70,
    enabled: true,
    refreshIntervalMinutes: 60,
    group: "normal",
  },
  {
    id: "rss-sciencedaily-top",
    name: "ScienceDaily Top Science",
    type: "rss",
    url: "https://www.sciencedaily.com/rss/top/science.xml",
    provider: "rss",
    category: "Science",
    language: "en",
    country: "US",
    authorityScore: 72,
    enabled: true,
    refreshIntervalMinutes: 120,
    group: "normal",
  },
  {
    id: "rss-sciencedaily-ai",
    name: "ScienceDaily AI",
    type: "rss",
    url: "https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml",
    provider: "rss",
    category: "Science",
    language: "en",
    country: "US",
    authorityScore: 72,
    enabled: true,
    refreshIntervalMinutes: 120,
    group: "normal",
  },
  {
    id: "rss-phys-org",
    name: "Phys.org",
    type: "rss",
    url: "https://phys.org/rss-feed/",
    provider: "rss",
    category: "Science",
    language: "en",
    country: "US",
    authorityScore: 70,
    enabled: true,
    refreshIntervalMinutes: 120,
    group: "normal",
  },
  {
    id: "rss-nasa",
    name: "NASA News",
    type: "official",
    url: "https://www.nasa.gov/news-release/feed/",
    provider: "rss",
    category: "Science",
    language: "en",
    country: "US",
    authorityScore: 88,
    enabled: true,
    refreshIntervalMinutes: 120,
    group: "normal",
  },
  {
    id: "rss-amazon-science",
    name: "Amazon Science",
    type: "official",
    url: "https://www.amazon.science/index.rss",
    provider: "rss",
    category: "Science",
    language: "en",
    country: "US",
    authorityScore: 85,
    enabled: true,
    refreshIntervalMinutes: 120,
    group: "normal",
  },
  {
    id: "rss-lwn",
    name: "LWN.net",
    type: "rss",
    url: "https://lwn.net/headlines/rss",
    provider: "rss",
    category: "OpenSource",
    language: "en",
    country: "US",
    authorityScore: 76,
    enabled: true,
    refreshIntervalMinutes: 120,
    group: "normal",
  },

  // ── Normal: research ──────────────────────────────────────────────
  {
    id: "arxiv-cs",
    name: "arXiv cs.AI / cs.CL / cs.LG / cs.DC / cs.CR",
    type: "api",
    url: "https://export.arxiv.org/api/query",
    provider: "arxiv",
    category: "Science",
    language: "en",
    authorityScore: 88,
    enabled: true,
    refreshIntervalMinutes: 120,
    group: "normal",
  },

  // ── Optional: Hugging Face hub (free-tier aware, off by default) ──
  {
    id: "hf-trending",
    name: "Hugging Face Trending",
    type: "api",
    url: "https://huggingface.co/api",
    provider: "huggingface",
    category: "AI",
    language: "en",
    authorityScore: 80,
    enabled: false,
    refreshIntervalMinutes: 60,
    group: "normal",
  },
];

/** Provider-level metadata per cost spec §100–103. */
export const PROVIDER_META = {
  rss: { label: "RSS / Atom", costType: "free", enabledByDefault: true },
  gdelt: { label: "GDELT DOC 2.0", costType: "free", enabledByDefault: true },
  github: { label: "GitHub REST", costType: "free-tier", enabledByDefault: true },
  hackernews: { label: "Hacker News Firebase", costType: "free", enabledByDefault: true },
  arxiv: { label: "arXiv API", costType: "free", enabledByDefault: true },
  huggingface: { label: "Hugging Face Hub", costType: "free-tier", enabledByDefault: false },
  newsapi: { label: "NewsAPI (paid/dev-tier)", costType: "paid", enabledByDefault: false },
} as const;
